### ISSUE TITLE
PVC storage is not working 

### ISSUE THREAD

**Issue by robin2008** [kubeflow/kfserving#1038]
/kind bug

**What steps did you take and what happened:**
1, install kfserving 0.4
2, create PV and PVC which contains the pre-trained models (here just use the example of sklearn)
3, create an inference services with below (the only change to the example is to use PVC, instead of GS):
```
apiVersion: "serving.kubeflow.org/v1alpha2"
kind: "InferenceService"
metadata:
  name: "sklearn-iris"
spec:
  default:
    predictor:
      sklearn:
        storageUri: "pvc://wmla-edi-kfserving/repo/sklearn"
```
4, the inference service could be created successfully (including the knative service), but the pod is failing at init stage.
Found below error logs:
```
oc get pods
NAME                                                              READY   STATUS                  RESTARTS   AGE
sklearn-iris-predictor-default-krjhr-deployment-5d4b8b8df5xd69d   0/2     Init:CrashLoopBackOff   10         27m

oc logs sklearn-iris-predictor-default-krjhr-deployment-5d4b8b8df5xd69d -c storage-initializer
[I 200823 13:04:26 initializer-entrypoint:13] Initializing, args: src_uri [/mnt/pvc/repo/sklearn] dest_path[ [/mnt/models]
[I 200823 13:04:26 storage:35] Copying contents of /mnt/pvc/repo/sklearn to local
Traceback (most recent call last):
  File "/storage-initializer/scripts/initializer-entrypoint", line 14, in <module>
    kfserving.Storage.download(src_uri, dest_path)
  File "/usr/local/lib/python3.7/site-packages/kfserving/storage.py", line 58, in download
    (_GCS_PREFIX, _S3_PREFIX, _LOCAL_PREFIX))
Exception: Cannot recognize storage type for /mnt/pvc/repo/sklearn
'gs://', 's3://', and 'file://' are the current available storage type.
```

**What did you expect to happen:**
PVC could used for storage w/o error.

**Anything else you would like to add:**
The POD is created with the PVC correctly.

```
oc describe pod sklearn-iris-predictor-default-krjhr-deployment-5d4b8b8df5xd69d
Name:         sklearn-iris-predictor-default-krjhr-deployment-5d4b8b8df5xd69d
Namespace:    kfserving-test
Priority:     0
Node:         ****************
Start Time:   Sun, 23 Aug 2020 20:38:07 +0800
Labels:       app=sklearn-iris-predictor-default-krjhr
              component=predictor
              endpoint=default
              model=sklearn-iris
              pod-template-hash=5d4b8b8df5
              serving.knative.dev/configuration=sklearn-iris-predictor-default
              serving.knative.dev/configurationGeneration=1
              serving.knative.dev/revision=sklearn-iris-predictor-default-krjhr
              serving.knative.dev/revisionUID=2813d166-83c6-404f-8e62-4f6789077f36
              serving.knative.dev/service=sklearn-iris-predictor-default
              serving.kubeflow.org/inferenceservice=sklearn-iris
Annotations:  autoscaling.knative.dev/class: kpa.autoscaling.knative.dev
              autoscaling.knative.dev/minScale: 1
              autoscaling.knative.dev/target: 1
              internal.serving.kubeflow.org/storage-initializer-sourceuri: pvc://wmla-edi-kfserving/repo/sklearn
              k8s.v1.cni.cncf.io/networks-status:
                [{
                    "name": "openshift-sdn",
                    "interface": "eth0",
                    "ips": [
                        "A.B.C.D"
                    ],
                    "dns": {},
                    "default-route": [
                        "A.B.C.D"
                    ]
                }]
              openshift.io/scc: restricted
              serving.knative.dev/creator: system:serviceaccount:kfserving-system:default
Status:       Pending
IP:           *.*.*.*
IPs:
  IP:           *.*.*.*
Controlled By:  ReplicaSet/sklearn-iris-predictor-default-krjhr-deployment-5d4b8b8df5
Init Containers:
  storage-initializer:
    Container ID:  cri-o://953d95558fd9be7ee8a2a9e43b077fd141144f6a32b7174fc31227d80325311f
    Image:         gcr.io/kfserving/storage-initializer:v0.4.0
    Image ID:      gcr.io/kfserving/storage-initializer@sha256:02e089391bdc50772393c8db2baa330f20147b7565355f5867f2291458cd60f7
    Port:          <none>
    Host Port:     <none>
    Args:
      /mnt/pvc/repo/sklearn
      /mnt/models
    State:       Waiting
      Reason:    CrashLoopBackOff
    Last State:  Terminated
      Reason:    Error
      Message:   [I 200823 13:04:26 initializer-entrypoint:13] Initializing, args: src_uri [/mnt/pvc/repo/sklearn] dest_path[ [/mnt/models]
[I 200823 13:04:26 storage:35] Copying contents of /mnt/pvc/repo/sklearn to local
Traceback (most recent call last):
  File "/storage-initializer/scripts/initializer-entrypoint", line 14, in <module>
    kfserving.Storage.download(src_uri, dest_path)
  File "/usr/local/lib/python3.7/site-packages/kfserving/storage.py", line 58, in download
    (_GCS_PREFIX, _S3_PREFIX, _LOCAL_PREFIX))
Exception: Cannot recognize storage type for /mnt/pvc/repo/sklearn
'gs://', 's3://', and 'file://' are the current available storage type.

      Exit Code:    1
      Started:      Sun, 23 Aug 2020 21:04:25 +0800
      Finished:     Sun, 23 Aug 2020 21:04:27 +0800
    Ready:          False
    Restart Count:  10
    Limits:
      cpu:     1
      memory:  1Gi
    Requests:
      cpu:        100m
      memory:     100Mi
    Environment:  <none>
    Mounts:
      /mnt/models from kfserving-provision-location (rw)
      /mnt/pvc from kfserving-pvc-source (ro)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-tz549 (ro)
Containers:
  kfserving-container:
    Container ID:
    Image:         gcr.io/kfserving/sklearnserver@sha256:240bcd68d68f0cbb038c43da1fd35420372ef17cb08b2b82e27fd2a4150050dc
    Image ID:
    Port:          8080/TCP
    Host Port:     0/TCP
    Args:
      --model_name=sklearn-iris
      --model_dir=/mnt/models
      --http_port=8080
    State:          Waiting
      Reason:       PodInitializing
    Ready:          False
    Restart Count:  0
    Limits:
      cpu:     1
      memory:  2Gi
    Requests:
      cpu:     1
      memory:  2Gi
    Environment:
      PORT:             8080
      K_REVISION:       sklearn-iris-predictor-default-krjhr
      K_CONFIGURATION:  sklearn-iris-predictor-default
      K_SERVICE:        sklearn-iris-predictor-default
    Mounts:
      /mnt/models from kfserving-provision-location (ro)
      /mnt/pvc from kfserving-pvc-source (ro)
      /var/log from knative-var-log (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-tz549 (ro)
  queue-proxy:
    Container ID:
    Image:          registry.redhat.io/openshift-serverless-1/serving-queue-rhel8@sha256:8d45d901a58ec5da58e97b5e0d38ce22a9318837a13926ef6c21bb5b81f0bcb0
    Image ID:
    Ports:          8022/TCP, 9090/TCP, 9091/TCP, 8012/TCP
    Host Ports:     0/TCP, 0/TCP, 0/TCP, 0/TCP
    State:          Waiting
      Reason:       PodInitializing
    Ready:          False
    Restart Count:  0
    Requests:
      cpu:      25m
    Readiness:  exec [/ko-app/queue -probe-period 0] delay=0s timeout=10s period=1s #success=1 #failure=3
    Environment:
      SERVING_NAMESPACE:                      kfserving-test
      SERVING_SERVICE:                        sklearn-iris-predictor-default
      SERVING_CONFIGURATION:                  sklearn-iris-predictor-default
      SERVING_REVISION:                       sklearn-iris-predictor-default-krjhr
      QUEUE_SERVING_PORT:                     8012
      CONTAINER_CONCURRENCY:                  0
      REVISION_TIMEOUT_SECONDS:               60
      SERVING_POD:                            sklearn-iris-predictor-default-krjhr-deployment-5d4b8b8df5xd69d (v1:metadata.name)
      SERVING_POD_IP:                          (v1:status.podIP)
      SERVING_LOGGING_CONFIG:                 {
                                                "level": "info",
                                                "development": false,
                                                "outputPaths": ["stdout"],
                                                "errorOutputPaths": ["stderr"],
                                                "encoding": "json",
                                                "encoderConfig": {
                                                  "timeKey": "ts",
                                                  "levelKey": "level",
                                                  "nameKey": "logger",
                                                  "callerKey": "caller",
                                                  "messageKey": "msg",
                                                  "stacktraceKey": "stacktrace",
                                                  "lineEnding": "",
                                                  "levelEncoder": "",
                                                  "timeEncoder": "iso8601",
                                                  "durationEncoder": "",
                                                  "callerEncoder": ""
                                                }
                                              }
      SERVING_LOGGING_LEVEL:
      SERVING_REQUEST_LOG_TEMPLATE:
      SERVING_REQUEST_METRICS_BACKEND:        prometheus
      TRACING_CONFIG_BACKEND:                 none
      TRACING_CONFIG_ZIPKIN_ENDPOINT:
      TRACING_CONFIG_STACKDRIVER_PROJECT_ID:
      TRACING_CONFIG_DEBUG:                   false
      TRACING_CONFIG_SAMPLE_RATE:             0.100000
      USER_PORT:                              8080
      SYSTEM_NAMESPACE:                       knative-serving
      METRICS_DOMAIN:                         knative.dev/internal/serving
      USER_CONTAINER_NAME:                    kfserving-container
      ENABLE_VAR_LOG_COLLECTION:              false
      VAR_LOG_VOLUME_NAME:                    knative-var-log
      INTERNAL_VOLUME_PATH:                   /var/knative-internal
      DOWNWARD_API_LABELS_PATH:               /etc/podinfo/labels
      SERVING_READINESS_PROBE:                {"tcpSocket":{"port":8080,"host":"127.0.0.1"},"successThreshold":1}
      ENABLE_PROFILING:                       false
      SERVING_ENABLE_PROBE_REQUEST_LOG:       false
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-tz549 (ro)
Conditions:
  Type              Status
  Initialized       False
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  knative-var-log:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
    SizeLimit:  <unset>
  default-token-tz549:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-tz549
    Optional:    false
  kfserving-pvc-source:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  wmla-edi-kfserving
    ReadOnly:   false
  kfserving-provision-location:
    Type:        EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
    SizeLimit:   <unset>
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/memory-pressure:NoSchedule
                 node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason     Age                              From                             Message
  ----     ------     ----                             ----                             -------
  Normal   Scheduled  <unknown>                        default-scheduler                Successfully assigned kfserving-test/sklearn-iris-predictor-default-krjhr-deployment-5d4b8b8df5xd69d to A.B.C.D
  Normal   Pulled     <invalid> (x5 over <invalid>)    kubelet, A.B.C.D Container image "gcr.io/kfserving/storage-initializer:v0.4.0" already present on machine
  Normal   Created    <invalid> (x5 over <invalid>)    kubelet, A.B.C.D  Created container storage-initializer
  Normal   Started    <invalid> (x5 over <invalid>)    kubelet, A.B.C.D  Started container storage-initializer
  Warning  BackOff    <invalid> (x116 over <invalid>)  kubelet, A.B.C.D  Back-off restarting failed container
```

**Environment:**

- Istio Version: 1.6.8
- Knative Version: 0.13.3
- KFServing Version: 0.4.0
- Kubeflow version:
- Kfdef:[k8s_istio/istio_dex/gcp_basic_auth/gcp_iap/aws/aws_cognito/ibm]
- Minikube version:
- Kubernetes version: (use `kubectl version`):
```
oc version
Client Version: 4.3.10-202003300415-6a90d0a
Server Version: 4.3.23
Kubernetes Version: v1.16.2+18cfcc9
```
- OS (e.g. from `/etc/os-release`):

**Comment by robin2008** [comment]
Yes, it is. I'm using wrong storageClassName and binds to wrong PV.
And the error message confused me.

**Comment by Bhavesh-Joshi** [comment]
> Yes, it is. I'm using wrong storageClassName and binds to wrong PV.
> And the error message confused me.

@robin2008 Can you please share the yaml which was worked for you while creating inferenceservice using pvc. Actually I having the exact same problem what you had face and described above. Thanks in advance!
