### ISSUE TITLE
Tabular Explainer e2e test failing

### ISSUE THREAD

**Issue by yuzisun** [kubeflow/kfserving#1052]
/kind bug

```
(base) C02YJ034JGH5:~ dsun20$ kubectl logs isvc-explainer-tabular-explainer-default-7cnkj-deployment-4q4hn -n kfserving-ci-e2e-test kfserving-container
[I 200828 13:12:28 font_manager:1423] Generating new fontManager, this may take some time...
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/local/lib/python3.7/runpy.py", line 142, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/local/lib/python3.7/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/alibiexplainer/alibiexplainer/__init__.py", line 15, in <module>
    from .explainer import AlibiExplainer
  File "/alibiexplainer/alibiexplainer/explainer.py", line 21, in <module>
    from alibiexplainer.anchor_images import AnchorImages
  File "/alibiexplainer/alibiexplainer/anchor_images.py", line 17, in <module>
    import alibi
  File "/usr/local/lib/python3.7/site-packages/alibi/__init__.py", line 1, in <module>
    from . import confidence, datasets, explainers, utils
  File "/usr/local/lib/python3.7/site-packages/alibi/explainers/__init__.py", line 11, in <module>
    from .kernel_shap import KernelShap
  File "/usr/local/lib/python3.7/site-packages/alibi/explainers/kernel_shap.py", line 11, in <module>
    from shap.common import DenseData, DenseDataWithIndex
ModuleNotFoundError: No module named 'shap.common'
```

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Istio Version:
- Knative Version:
- KFServing Version:
- Kubeflow version:
- Kfdef:[k8s_istio/istio_dex/gcp_basic_auth/gcp_iap/aws/aws_cognito/ibm]
- Minikube version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by yuzisun** [comment]
@cliveseldon Can you help take a look ?

**Comment by cliveseldon** [comment]
shap must be missing from the image

**Comment by cliveseldon** [comment]
@yuzisun which image is it running?
