### ISSUE TITLE
Could not use KFServing with Kubeflow v1.1

### ISSUE THREAD

**Issue by panchul** [kubeflow/kfserving#1108]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]

When I try to run samples on a Kubeflow cluster(v1.1), I could not create kfserving crd. For example:

```
$ cd docs/samples/onnx 
$ kubectl apply -f onnx.yaml
Error from server: error when creating "onnx.yaml": admission webhook "inferenceservice.kfserving-webhook-server.validator" denied the request: Cannot create the Inferenceservice "style-sample" in namespace "default": the namespace lacks label "serving.kubeflow.org/inferenceservice: enabled"
```

**What did you expect to happen:**

```
$ kubectl apply -f onnx.yaml 
  inferenceservice.serving.kubeflow.org/style-sample configured
```

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

I tried adding the label `"serving.kubeflow.org/inferenceservice: enabled"`, it did not help much. 

The cluster was created on Azure Stack, using aks-engine:

```
$ aks-engine version
Version: v0.55.4
GitCommit: 0b2df8a7a
GitTreeState: clean

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.11", GitCommit:"15a22a6692b712eff8b057892da0640afa97d061", GitTreeState:"clean", BuildDate:"2020-09-11T23:40:30Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.11", GitCommit:"15a22a6692b712eff8b057892da0640afa97d061", GitTreeState:"clean", BuildDate:"2020-09-11T23:40:30Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

Kubeflow manifests:

- https://github.com/kubeflow/kfctl/releases/download/v1.1.0/kfctl_v1.1.0-0-g9a3621e_linux.tar.gz
- https://raw.githubusercontent.com/kubeflow/manifests/v1.1-branch/kfdef/kfctl_k8s_istio.v1.1.0.yaml

**Environment:**

- Istio Version:
- Knative Version:
- KFServing Version:
- Kubeflow version: v1.1
- Kfdef:[k8s_istio/istio_dex/gcp_basic_auth/gcp_iap/aws/aws_cognito/ibm]
- Minikube version:
- Kubernetes version: (use `kubectl version`): v1.17.11
- OS (e.g. from `/etc/os-release`): 
- Azure Stack, aks-engine Version: v0.55.4

**Comment by ellistarn** [comment]
What did you add the label to? The namespace needs to be labeled.

**Comment by panchul** [comment]
@ellistarn , hm... the doc did not mention it, I thought they would be by default labeled enable.
I did try labeling them manually, (`label namespaces default serving.kubeflow.org/inferenceservice=enabled`), but I could not get the service host as I expected:
```
$ kubectl apply -f onnx.yaml
inferenceservice.serving.kubeflow.org/style-sample created
$ export MODEL_NAME=style-sample
$ export SERVICE_HOSTNAME=$(kubectl get inferenceservice ${MODEL_NAME} -o jsonpath='{.status.url}' | cut -d "/" -f 3)
$ echo $SERVICE_HOSTNAME
$ kubectl get inferenceservice
NAME           URL   READY   DEFAULT TRAFFIC   CANARY TRAFFIC   AGE
style-sample         False                                      2m42s
```
The error for inferenceservice I see is `Configuration "style-sample-predictor-default" does not have any ready Revision.`

Any suggestions?

**Comment by panchul** [comment]
Here is the `style-sample` being deployed. It does not go to 'Ready' state.

```
$ kubectl describe inferenceservice style-sample
Name:         style-sample
Namespace:    default
Labels:       <none>
Annotations:  kubectl.kubernetes.io/last-applied-configuration:
                {"apiVersion":"serving.kubeflow.org/v1alpha2","kind":"InferenceService","metadata":{"annotations":{},"name":"style-sample","namespace":"de...
API Version:  serving.kubeflow.org/v1alpha2
Kind:         InferenceService
Metadata:
  Creation Timestamp:  2020-09-29T22:25:18Z
  Generation:          1
  Resource Version:    3578216
  Self Link:           /apis/serving.kubeflow.org/v1alpha2/namespaces/default/inferenceservices/style-sample
  UID:                 777682c9-8454-4260-832b-f1fb8b1fcb1a
Spec:
  Default:
    Predictor:
      Onnx:
        Resources:
          Limits:
            Cpu:     1
            Memory:  2Gi
          Requests:
            Cpu:          1
            Memory:       2Gi
        Runtime Version:  v0.5.1
        Storage Uri:      https://kfserving.blob.core.windows.net/examples/onnx/style/model.onnx
Status:
  Canary:
  Conditions:
    Last Transition Time:  2020-09-29T22:25:19Z
    Message:               Configuration "style-sample-predictor-default" does not have any ready Revision.
    Reason:                RevisionMissing
    Status:                False
    Type:                  DefaultPredictorReady
    Last Transition Time:  2020-09-29T22:25:19Z
    Message:               Failed to reconcile predictor
    Reason:                PredictorHostnameUnknown
    Status:                False
    Type:                  Ready
    Last Transition Time:  2020-09-29T22:25:18Z
    Message:               Failed to reconcile predictor
    Reason:                PredictorHostnameUnknown
    Status:                False
    Type:                  RoutesReady
  Default:
    Predictor:
      Name:  style-sample-predictor-default-whrfm
Events:      <none>
```

**Comment by yuzisun** [comment]
@panchul please check this issue https://github.com/kubeflow/kfserving/issues/1067, that onnx model url no longer works.

/cc @tduffy000 @rakelkar

**Comment by tduffy000** [comment]
@panchul if you want a working example (using the ONNX framework with the iris model), you can use this one for now https://github.com/tduffy000/kfserving-uri-examples/blob/master/crd/onnx.yaml (might need to address the namespace discrepancy mentioned above); I'm working on addressing the example in the repo currently.

**Comment by panchul** [comment]
@tduffy000 , thanks! I will try.

**Comment by yuzisun** [comment]
> @tduffy000 , thanks! I will try.

@panchul I think the kfserving version you are running does not support http storage uri yet. You might need to download the model from that url and host it somewhere else like gcs or s3 bucket .

**Comment by panchul** [comment]
@yuzisun , I saw it was ok with 'file://', so I just downloaded it locally, and it seem to create an inference object, but it is not functioning. What are the 'Revision's, the error message says they are missing, is it something I need to create? How?

```
$ ls -la model.onnx
-rw-r----- 1 azureuser azureuser 3465 Sep 30 01:54 model.onnx

$ cat onnx.yaml
apiVersion: serving.kubeflow.org/v1alpha2
kind: InferenceService
metadata:
  name: tensorflow-from-uri
spec:
  default:
    predictor:
      onnx:
        #storageUri: https://github.com/tduffy000/kfserving-uri-examples/blob/master/onnx/frozen/model.onnx?raw=true
        storageUri: file://model.onnx

$ kubectl apply -f onnx.yaml -n kfserving-test
inferenceservice.serving.kubeflow.org/tensorflow-from-uri created

$ kubectl get inferenceservice -n kfserving-test
NAME                  URL   READY   DEFAULT TRAFFIC   CANARY TRAFFIC   AGE
tensorflow-from-uri         False                                      60s

$ kubectl describe inferenceservice -n kfserving-test tensorflow-from-uri
Name:         tensorflow-from-uri
Namespace:    kfserving-test
Labels:       <none>
Annotations:  kubectl.kubernetes.io/last-applied-configuration:
                {"apiVersion":"serving.kubeflow.org/v1alpha2","kind":"InferenceService","metadata":{"annotations":{},"name":"tensorflow-from-uri","namespa...
API Version:  serving.kubeflow.org/v1alpha2
Kind:         InferenceService
Metadata:
  Creation Timestamp:  2020-09-30T01:55:25Z
  Generation:          1
  Resource Version:    18875
  Self Link:           /apis/serving.kubeflow.org/v1alpha2/namespaces/kfserving-test/inferenceservices/tensorflow-from-uri
  UID:                 c6e9a484-738e-43d8-953e-52bc0a2906e5
Spec:
  Default:
    Predictor:
      Onnx:
        Resources:
          Limits:
            Cpu:     1
            Memory:  2Gi
          Requests:
            Cpu:          1
            Memory:       2Gi
        Runtime Version:  v0.5.1
        Storage Uri:      file://model.onnx
Status:
  Canary:
  Conditions:
    Last Transition Time:  2020-09-30T01:55:27Z
    Message:               Configuration "tensorflow-from-uri-predictor-default" does not have any ready Revision.
    Reason:                RevisionMissing
    Status:                False
    Type:                  DefaultPredictorReady
    Last Transition Time:  2020-09-30T01:55:27Z
    Message:               Failed to reconcile predictor
    Reason:                PredictorHostnameUnknown
    Status:                False
    Type:                  Ready
    Last Transition Time:  2020-09-30T01:55:26Z
    Message:               Failed to reconcile predictor
    Reason:                PredictorHostnameUnknown
    Status:                False
    Type:                  RoutesReady
  Default:
    Predictor:
      Name:  tensorflow-from-uri-predictor-default-dkllp
Events:      <none>
```

**Comment by panchul** [comment]
@yuzisun , I feel I am very close to make it work, but for some reason gs:// model uri does not work. I uploaded the model to a bucket public, its https uri https://storage.googleapis.com/alexbucket4misc/model.onnx is fine(from a browser), but when I reference  `gs://alexbucket4misc/model.onnx`, I get an error(`Anonymous credentials cannot be refreshed`).

Am I doing something wrong, or missing anything? I appreciate some hints.

```
$ cat onnx.yaml
apiVersion: serving.kubeflow.org/v1alpha2
kind: InferenceService
metadata:
  name: tensorflow-from-uri
spec:
  default:
    predictor:
      onnx:
        storageUri: gs://alexbucket4misc/model.onnx


$ k logs  -n kfserving-test tensorflow-from-uri-predictor-default-vng54-deployment-846mp4z5 storage-initializer
[I 200930 17:48:51 initializer-entrypoint:13] Initializing, args: src_uri [gs://alexbucket4misc/model.onnx] dest_path[ [/mnt/models]
[I 200930 17:48:51 storage:35] Copying contents of gs://alexbucket4misc/model.onnx to local
[I 200930 17:48:54 _metadata:95] Compute Engine Metadata server unavailable onattempt 1 of 3
[I 200930 17:48:57 _metadata:95] Compute Engine Metadata server unavailable onattempt 2 of 3
[I 200930 17:49:00 _metadata:95] Compute Engine Metadata server unavailable onattempt 3 of 3
[I 200930 17:49:00 requests:335] Refreshing credentials due to a 401 response. Attempt 1/2.
Traceback (most recent call last):
  File "/storage-initializer/scripts/initializer-entrypoint", line 14, in <module>
    kfserving.Storage.download(src_uri, dest_path)
  File "/usr/local/lib/python3.7/site-packages/kfserving/storage.py", line 48, in download
    Storage._download_gcs(uri, out_dir)
  File "/usr/local/lib/python3.7/site-packages/kfserving/storage.py", line 100, in _download_gcs
    for blob in blobs:
  File "/usr/local/lib/python3.7/site-packages/google/api_core/page_iterator.py", line 212, in _items_iter
    for page in self._page_iter(increment=False):
  File "/usr/local/lib/python3.7/site-packages/google/api_core/page_iterator.py", line 243, in _page_iter
    page = self._next_page()
  File "/usr/local/lib/python3.7/site-packages/google/api_core/page_iterator.py", line 369, in _next_page
    response = self._get_next_page_response()
  File "/usr/local/lib/python3.7/site-packages/google/api_core/page_iterator.py", line 419, in _get_next_page_response
    method=self._HTTP_METHOD, path=self.path, query_params=params
  File "/usr/local/lib/python3.7/site-packages/google/cloud/_http.py", line 419, in api_request
    timeout=timeout,
  File "/usr/local/lib/python3.7/site-packages/google/cloud/_http.py", line 277, in _make_request
    method, url, headers, data, target_object, timeout=timeout
  File "/usr/local/lib/python3.7/site-packages/google/cloud/_http.py", line 315, in _do_request
    url=url, method=method, headers=headers, data=data, timeout=timeout
  File "/usr/local/lib/python3.7/site-packages/google/auth/transport/requests.py", line 347, in request
    self.credentials.refresh(auth_request)
  File "/usr/local/lib/python3.7/site-packages/google/auth/credentials.py", line 148, in refresh
    raise ValueError("Anonymous credentials cannot be refreshed.")
ValueError: Anonymous credentials cannot be refreshed.
```

**Comment by panchul** [comment]
@yuzisun , is there any particular path expected? I am getting a different error, about the URI, which is what that file has(and I can access it via http ok)

```
      Message:   [I 201008 16:46:11 initializer-entrypoint:13] Initializing, args: src_uri [gs://alexbucket4misc/model.onnx] dest_path[ [/mnt/models]
[I 201008 16:46:11 storage:35] Copying contents of gs://alexbucket4misc/model.onnx to local
Traceback (most recent call last):
  File "/storage-initializer/scripts/initializer-entrypoint", line 14, in <module>
    kfserving.Storage.download(src_uri, dest_path)
  File "/usr/local/lib/python3.7/site-packages/kfserving/storage.py", line 48, in download
    Storage._download_gcs(uri, out_dir)
  File "/usr/local/lib/python3.7/site-packages/kfserving/storage.py", line 116, in _download_gcs
    The path or model %s does not exist." % (uri))
RuntimeError: Failed to fetch model. The path or model gs://alexbucket4misc/model.onnx does not exist.
```

**Comment by yuzisun** [comment]
pinging our onnx expert @tduffy000 :)

**Comment by yuzisun** [comment]
@panchul I think for gcs storage you need to specify the storage uri one level up which contains the `model.onnx` file.

I also uploaded the same model to `gs://kfserving-examples/onnx/style` so the example should work now.
