### ISSUE TITLE
Installed KFServing SDK 0.4 but getting import error while running the custom built image

### ISSUE THREAD

**Issue by yuzisun** [kubeflow/kfserving#1117]
/kind bug

**What steps did you take and what happened:**
Run a custom built image with KFServing SDK 0.4.
```
Traceback (most recent call last):
  File "/python3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/python3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/job/blambda-function/image_transformer_v2/__main__.py", line 15, in <module>
    import kfserving
  File "/python3/lib/python3.7/site-packages/kfserving/__init__.py", line 18, in <module>
    from .storage import Storage
  File "/python3/lib/python3.7/site-packages/kfserving/storage.py", line 23, in <module>
    from google.cloud import storage
  File "/python3/lib/python3.7/site-packages/google/cloud/storage/__init__.py", line 39, in <module>
    from google.cloud.storage.batch import Batch
  File "/python3/lib/python3.7/site-packages/google/cloud/storage/batch.py", line 31, in <module>
    from google.cloud.storage._http import Connection
  File "/python3/lib/python3.7/site-packages/google/cloud/storage/_http.py", line 17, in <module>
    from google.cloud import _http
  File "/python3/lib/python3.7/site-packages/google/cloud/_http.py", line 22, in <module>
    from six.moves import collections_abc
ImportError: cannot import name 'collections_abc' from 'six.moves' (unknown location)
```

**What did you expect to happen:**

**Anything else you would like to add:**
We have fixed this in master branch but looks like we need to patch the setup.py in 0.4 branch and release a new minor version

**Environment:**

- Istio Version:
- Knative Version:
- KFServing Version:
- Kubeflow version:
- Kfdef:[k8s_istio/istio_dex/gcp_basic_auth/gcp_iap/aws/aws_cognito/ibm]
- Minikube version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by yuzisun** [comment]
fixed in KFServing SDK 0.4.1
