### ISSUE TITLE
Cannot recognize storage type for /mnt/pvc, inference service for triton

### ISSUE THREAD

**Issue by ontheway16** [kubeflow/kfserving#1298]
Trying to install a custom model with triton 20.08;
```
~$ kubectl get all |grep triton
pod/test-triton-predictor-default-00002-deployment-55bbbb5d8c-jqctb   0/3     Init:CrashLoopBackOff   82         6h47m
service/test-triton-predictor-default-00001           ClusterIP      10.105.229.246   <none>                                                 80/TCP                              6h47m
service/test-triton-predictor-default-00001-private   ClusterIP      10.104.28.46     <none>                                                 80/TCP,9090/TCP,9091/TCP,8022/TCP   6h47m
service/test-triton-predictor-default-00002           ClusterIP      10.104.46.220    <none>                                                 80/TCP                              6h47m
service/test-triton-predictor-default-00002-private   ClusterIP      10.103.252.125   <none>                                                 80/TCP,9090/TCP,9091/TCP,8022/TCP   6h47m
deployment.apps/test-triton-predictor-default-00001-deployment   0/0     0            0           6h47m
deployment.apps/test-triton-predictor-default-00002-deployment   0/1     1            0           6h47m
replicaset.apps/test-triton-predictor-default-00001-deployment-64b9445d4    0         0         0       6h47m
replicaset.apps/test-triton-predictor-default-00002-deployment-55bbbb5d8c   1         1         0       6h47m
route.serving.knative.dev/test-triton-predictor-default   http://test-triton-predictor-default.default.192.168.1.235.xip.io   False   RevisionMissing
revision.serving.knative.dev/test-triton-predictor-default-00001   test-triton-predictor-default   test-triton-predictor-default-00001   1            False   PodInitializing
revision.serving.knative.dev/test-triton-predictor-default-00002   test-triton-predictor-default   test-triton-predictor-default-00002   2            False   PodInitializing
configuration.serving.knative.dev/test-triton-predictor-default   test-triton-predictor-default-00002                                       False   RevisionFailed
service.serving.knative.dev/test-triton-predictor-default   http://test-triton-predictor-default.default.192.168.1.235.xip.io   test-triton-predictor-default-00002                                       False   RevisionMissing

```

```
~$ kubectl describe pods test-triton-predictor-default-00002-deployment-55bbbb5d8c-jqctb
Name:         test-triton-predictor-default-00002-deployment-55bbbb5d8c-jqctb
Namespace:    default
Priority:     0
Node:         masternode01/192.168.1.133
Start Time:   Wed, 13 Jan 2021 18:34:11 +0300
Labels:       app=test-triton-predictor-default-00002
              component=predictor
              istio.io/rev=default
              pod-template-hash=55bbbb5d8c
              security.istio.io/tlsMode=istio
              service.istio.io/canonical-name=test-triton-predictor-default
              service.istio.io/canonical-revision=test-triton-predictor-default-00002
              serving.knative.dev/configuration=test-triton-predictor-default
              serving.knative.dev/configurationGeneration=2
              serving.knative.dev/revision=test-triton-predictor-default-00002
              serving.knative.dev/revisionUID=7b691377-0989-42df-980a-7eafad8cabd4
              serving.knative.dev/service=test-triton-predictor-default
              serving.kubeflow.org/inferenceservice=test-triton
Annotations:  autoscaling.knative.dev/class: kpa.autoscaling.knative.dev
              autoscaling.knative.dev/minScale: 1
              internal.serving.kubeflow.org/storage-initializer-sourceuri: pvc://triton-models-claim/home/alper/models
              prometheus.io/path: /stats/prometheus
              prometheus.io/port: 15020
              prometheus.io/scrape: true
              serving.knative.dev/creator: system:serviceaccount:kfserving-system:default
              sidecar.istio.io/status:
                {"version":"8e6e902b765af607513b28d284940ee1421e9a0d07698741693b2663c7161c11","initContainers":["istio-init"],"containers":["istio-proxy"]...
Status:       Pending
IP:           10.244.0.176
IPs:
  IP:           10.244.0.176
Controlled By:  ReplicaSet/test-triton-predictor-default-00002-deployment-55bbbb5d8c
Init Containers:
  storage-initializer:
    Container ID:  docker://cc03d28e20a7e3930a4a87f269d994329a77a46866bec8ea9f77edd3b86f54fc
    Image:         gcr.io/kfserving/storage-initializer:v0.5.0-rc1
    Image ID:      docker-pullable://gcr.io/kfserving/storage-initializer@sha256:bd5ad7ca7a42c127f046362dcf3ab48db0475438544911fb04b29b253c6ebdcd
    Port:          <none>
    Host Port:     <none>
    Args:
      /mnt/pvc/home/alper/models
      /mnt/models
    State:       Waiting
      Reason:    CrashLoopBackOff
    Last State:  Terminated
      Reason:    Error
      Message:   [I 210113 22:16:27 initializer-entrypoint:13] Initializing, args: src_uri [/mnt/pvc/home/alper/models] dest_path[ [/mnt/models]
[I 210113 22:16:27 storage:43] Copying contents of /mnt/pvc/home/alper/models to local
Traceback (most recent call last):
  File "/storage-initializer/scripts/initializer-entrypoint", line 14, in <module>
    kfserving.Storage.download(src_uri, dest_path)
  File "/usr/local/lib/python3.7/site-packages/kfserving/storage.py", line 74, in download
    (_GCS_PREFIX, _S3_PREFIX, _LOCAL_PREFIX, _HTTP_PREFIX))
Exception: Cannot recognize storage type for /mnt/pvc/home/alper/models
'gs://', 's3://', 'file://', and 'http(s)://' are the current available storage type.

      Exit Code:    1
      Started:      Thu, 14 Jan 2021 01:16:26 +0300
      Finished:     Thu, 14 Jan 2021 01:16:27 +0300
    Ready:          False
...
...
    Environment:  <none>
    Mounts:
      /mnt/models from kfserving-provision-location (rw)
      /mnt/pvc from kfserving-pvc-source (ro)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-lxw7l (ro)

...

...
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-lxw7l (ro)
  istio-proxy:

...
...
    State:          Waiting
      Reason:       PodInitializing
    Ready:          False
    Restart Count:  0
    Limits:
      cpu:     2
      memory:  1Gi
    Requests:
      cpu:      100m
      memory:   128Mi
    Readiness:  http-get http://:15021/healthz/ready delay=1s timeout=1s period=2s #success=1 #failure=30
    Environment:
      JWT_POLICY:                    first-party-jwt
      PILOT_CERT_PROVIDER:           istiod
      CA_ADDR:                       istiod.istio-system.svc:15012
      POD_NAME:                      test-triton-predictor-default-00002-deployment-55bbbb5d8c-jqctb (v1:metadata.name)
      POD_NAMESPACE:                 default (v1:metadata.namespace)

...
...
Conditions:
  Type              Status
  Initialized       False 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  default-token-lxw7l:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-lxw7l
    Optional:    false
  kfserving-pvc-source:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  triton-models-claim
    ReadOnly:   false
  kfserving-provision-location:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
  istio-envoy:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     Memory
    SizeLimit:  <unset>
  istio-data:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
  istio-podinfo:
    Type:  DownwardAPI (a volume populated by information about the pod)
    Items:
      metadata.labels -> labels
      metadata.annotations -> annotations
  istiod-ca-cert:
    Type:        ConfigMap (a volume populated by a ConfigMap)
    Name:        istio-ca-root-cert
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason   Age                       From                   Message
  ----     ------   ----                      ----                   -------
  Warning  BackOff  4m11s (x1841 over 6h44m)  kubelet, masternode01  Back-off restarting failed container

```

Apparently, it fails to copy /models contents, but;

```
~$ kubectl get pv
NAME                    CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS      CLAIM                         STORAGECLASS    REASON   AGE
example-local-pv        50Gi       RWO            Retain           Available                                 local-storage            14d
triton-models-volume    2Gi        RWO            Retain           Bound       default/triton-models-claim   manual                   6h50m
triton-plugins-volume   2Gi        RWO            Retain           Available                                 manual                   6h50m
~$ kubectl get pvc
NAME                   STATUS    VOLUME                 CAPACITY   ACCESS MODES   STORAGECLASS    AGE
pvc-local-claim        Pending                                                    local-storage   14d
triton-models-claim    Bound     triton-models-volume   2Gi        RWO            manual          6h49m
triton-plugins-claim   Pending                                                    manual          6h49m
```

Inference servers; bert is working on cpu and uses gs://, and this node is installed with 2 gpus;

```
~$ kubectl get inferenceservice
NAME          URL                                           READY   AGE
bert-v2       http://bert-v2.default.192.168.1.235.xip.io   True    12h
test-triton                                                 False   6h59m
```
Inference service yaml file;
```
~$ cat triton_yolov4inf.yaml 
apiVersion: "serving.kubeflow.org/v1beta1"
kind: "InferenceService"
metadata:
...
      resources:
        limits:
          nvidia.com/gpu: "1"
          memory: 1Gi
        requests:
          nvidia.com/gpu: "1"
          memory: 1Gi
      storageUri: "pvc://triton-models-claim/home/alper/models"
```

Before of this error, run another test by installing triton server as a pod, with same pv and pvc yaml files, (then deleted the service), and installed  this inferenceservice above, but I simply cannot find whats wrong or missing. All seems fine to my eye..?

**Comment by jbottum** [comment]
@ontheway16 FYI, Arrikto provides a storage class that is integrated (and supported) in advanced Kubeflow workflows.  This architecture enables you to use the operational, performance & cost benefits of local NVMe disks.  It might be worth a call to discuss your use cases.

**Comment by cliveseldon** [comment]
Can you try with `file://` as the prefix?

**Comment by ontheway16** [comment]
Solved. I have modified the storageUri to:
`storageUri: "pvc://triton-models-claim"`
(and later, also modified gpu ram limits, to 5Gib, since limit should be higher than the request, as far as I understand, other wise pod status returns `OOMKilled`

**Comment by ontheway16** [comment]
Solved. I have modified the storageUri to:
`storageUri: "pvc://triton-models-claim"`
(and later, also modified gpu ram limits, to 5Gib, since limit should be higher than the request, as far as I understand, other wise pod status returns `OOMKilled`
