### ISSUE TITLE
Art explainer crashes the kfserving controller

### ISSUE THREAD

**Issue by yuzisun** [kubeflow/kfserving#1310]
/kind bug

**What steps did you take and what happened:**
http://86308603-argo-argo-5ce9-1162466691.us-west-2.elb.amazonaws.com/workflows/kubeflow-test-infra/kubeflow-kfserving-presubmit-e2e-1306-d0f3432-5360-280e?tab=workflow&nodeId=kubeflow-kfserving-presubmit-e2e-1306-d0f3432-5360-280e-159579293&sidePanel=logs%3Akubeflow-kfserving-presubmit-e2e-1306-d0f3432-5360-280e-159579293%3Amain

```
{"level":"info","ts":1611193722.1990366,"logger":"inferenceservice-v1beta1-mutating-webhook","msg":"Defaulting InferenceService","namespace":"kfserving-ci-e2e-test","isvc":{
"containers":[{"name":"kfserving-container","image":"aipipeline/art-server:mnist-predictor","command":["python","-m","sklearnserver","--model_name","art-explainer","--model_
dir","file://sklearnserver/sklearnserver/example_model"],"resources":{"limits":{"cpu":"1","memory":"2Gi"},"requests":{"cpu":"1","memory":"2Gi"}}}]}}
2021/01/21 01:48:42 http: panic serving 192.168.102.112:49516: runtime error: invalid memory address or nil pointer dereference
goroutine 757 [running]:
net/http.(*conn).serve.func1(0xc000be6320)
        /usr/local/go/src/net/http/server.go:1772 +0x139
panic(0x175c340, 0x28ab210)
        /usr/local/go/src/runtime/panic.go:975 +0x3e3
github.com/kubeflow/kfserving/pkg/apis/serving/v1alpha2.(*InferenceService).ConvertFrom(0xc000275680, 0x1bcf900, 0xc000af6000, 0x1bcf900, 0xc000af6000)
        /go/src/github.com/kubeflow/kfserving/pkg/apis/serving/v1alpha2/inferenceservice_conversion.go:346 +0x2eb
sigs.k8s.io/controller-runtime/pkg/webhook/conversion.(*Webhook).convertObject(0xc00002ddb0, 0x1baca80, 0xc000af6000, 0x1bac9c0, 0xc000275680, 0x1bac9c0, 0xc000275680)
        /go/pkg/mod/github.com/zchee/sigs.k8s-controller-runtime@v0.6.1-0.20200623114430-46812d3a0a50/pkg/webhook/conversion/conversion.go:142 +0x7bc
sigs.k8s.io/controller-runtime/pkg/webhook/conversion.(*Webhook).handleConvertRequest(0xc00002ddb0, 0xc000e40540, 0xc000754cc0, 0x0, 0x0)
        /go/pkg/mod/github.com/zchee/sigs.k8s-controller-runtime@v0.6.1-0.20200623114430-46812d3a0a50/pkg/webhook/conversion/conversion.go:107 +0x1f8
sigs.k8s.io/controller-runtime/pkg/webhook/conversion.(*Webhook).ServeHTTP(0xc00002ddb0, 0x7f6851c8fad8, 0xc000b88190, 0xc000ea7300)
        /go/pkg/mod/github.com/zchee/sigs.k8s-controller-runtime@v0.6.1-0.20200623114430-46812d3a0a50/pkg/webhook/conversion/conversion.go:74 +0x10b
github.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerInFlight.func1(0x7f6851c8fad8, 0xc000b88190, 0xc000ea7300)
        /go/pkg/mod/github.com/prometheus/client_golang@v1.6.0/prometheus/promhttp/instrument_server.go:40 +0xab
net/http.HandlerFunc.ServeHTTP(0xc000315e60, 0x7f6851c8fad8, 0xc000b88190, 0xc000ea7300)
        /usr/local/go/src/net/http/server.go:2012 +0x44
github.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerCounter.func1(0x1bddf00, 0xc0005f62a0, 0xc000ea7300)
        /go/pkg/mod/github.com/prometheus/client_golang@v1.6.0/prometheus/promhttp/instrument_server.go:100 +0xda
net/http.HandlerFunc.ServeHTTP(0xc0003e0000, 0x1bddf00, 0xc0005f62a0, 0xc000ea7300)
        /usr/local/go/src/net/http/server.go:2012 +0x44
github.com/prometheus/client_golang/prometheus/promhttp.InstrumentHandlerDuration.func2(0x1bddf00, 0xc0005f62a0, 0xc000ea7300)
        /go/pkg/mod/github.com/prometheus/client_golang@v1.6.0/prometheus/promhttp/instrument_server.go:76 +0xb2
net/http.HandlerFunc.ServeHTTP(0xc0003e0270, 0x1bddf00, 0xc0005f62a0, 0xc000ea7300)
        /usr/local/go/src/net/http/server.go:2012 +0x44
net/http.(*ServeMux).ServeHTTP(0xc000601cc0, 0x1bddf00, 0xc0005f62a0, 0xc000ea7300)
```

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Istio Version:
- Knative Version:
- KFServing Version: master
- Kubeflow version:
- Kfdef:[k8s_istio/istio_dex/gcp_basic_auth/gcp_iap/aws/aws_cognito/ibm]
- Minikube version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by yuzisun** [comment]
I think it is probably due to the fact that art explainer is not implemented on v1alpha2 so `dst.Spec.Default.Explainer` is null 
https://github.com/kubeflow/kfserving/blob/master/pkg/apis/serving/v1alpha2/inferenceservice_conversion.go#L346

**Comment by Tomcli** [comment]
I thought v1alpha2 is going to be deprecated in the future releases so I didn't add it to the PR. Not sure is there a way to opt-out the converter to avoid this error, but I can add the v1alpha2 api if that's required.

**Comment by yuzisun** [comment]
@Tomcli I think we do not need to add back to v1alpha2, we just need a null check if the explainer does not exist on v1alpha2.
            if dst.Spec.Default.Explainer != nil {
		dst.Spec.Default.Explainer.ServiceAccountName = src.Spec.Explainer.PodSpec.ServiceAccountName
		dst.Spec.Default.Explainer.MinReplicas = src.Spec.Explainer.MinReplicas
		dst.Spec.Default.Explainer.MaxReplicas = src.Spec.Explainer.MaxReplicas
		if src.Spec.Explainer.ContainerConcurrency != nil {
			dst.Spec.Default.Explainer.Parallelism = int(*src.Spec.Explainer.ContainerConcurrency)
		}
           }
