### ISSUE TITLE
[Test] Fix lightgbm test in new test-infra

### ISSUE THREAD

**Issue by PatrickXYS** [kubeflow/kfserving#1335]
During the process I helped kfserving migrate to new test-infra, noticed that lightgbm failed every time, and to mitigate the issue, I disabled it in the pytest.

I'm working on the lightgbm test cases, and see if I can reproduce locally. 

Need to spend time and dig into it 

Detailed can be found https://github.com/kubeflow/kfserving/pull/1329#issuecomment-770325947

/cc @yuzisun 
/assign

**Comment by yuzisun** [comment]
@lynnmatrix not sure if there is some dependency change, but seems now lightgbmserver is broken and I can replicate the issue with `make deploy-dev-lgb` and in the log I can see

```
[E 210202 07:01:10 web:1793] Uncaught exception POST /v1/models/lightgbm-iris:predict (127.0.0.1)
    HTTPServerRequest(protocol='http', host='lightgbm-iris-predictor-default.default.svc.cluster.local', method='POST', uri='/v1/models/lightgbm-iris:predict', version='HTTP/1.1', remote_ip='127.0.0.1')
    Traceback (most recent call last):
      File "/lgbserver/lgbserver/model.py", line 51, in predict
        result = self._booster.predict(inputs)
      File "/usr/local/lib/python3.7/site-packages/lightgbm/basic.py", line 2415, in predict
        data_has_header, is_reshape)
      File "/usr/local/lib/python3.7/site-packages/lightgbm/basic.py", line 504, in predict
        data = _data_from_pandas(data, None, None, self.pandas_categorical)[0]
      File "/usr/local/lib/python3.7/site-packages/lightgbm/basic.py", line 318, in _data_from_pandas
        cat_cols = list(data.select_dtypes(include=['category']).columns)
      File "/usr/local/lib/python3.7/site-packages/pandas/core/frame.py", line 3442, in select_dtypes
        include_these = Series(not bool(include), index=self.columns)
      File "/usr/local/lib/python3.7/site-packages/pandas/core/series.py", line 314, in __init__
        data = sanitize_array(data, index, dtype, copy, raise_cast_failure=True)
      File "/usr/local/lib/python3.7/site-packages/pandas/core/internals/construction.py", line 712, in sanitize_array
        subarr = construct_1d_arraylike_from_scalar(value, len(index), dtype)
      File "/usr/local/lib/python3.7/site-packages/pandas/core/dtypes/cast.py", line 1233, in construct_1d_arraylike_from_scalar
        subarr = np.empty(length, dtype=dtype)
    TypeError: Cannot interpret '<attribute 'dtype' of 'numpy.generic' objects>' as a data type
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/usr/local/lib/python3.7/site-packages/tornado/web.py", line 1704, in _execute
        result = await result
      File "/kfserving/kfserving/handlers/http.py", line 59, in post
        response = (await model.predict(request)) if inspect.iscoroutinefunction(model.predict) else model.predict(request)
      File "/lgbserver/lgbserver/model.py", line 54, in predict
        raise Exception("Failed to predict %s" % e)
    Exception: Failed to predict Cannot interpret '<attribute 'dtype' of 'numpy.generic' objects>' as a data type
[E 210202 07:01:10 web:2243] 500 POST /v1/models/lightgbm-iris:predict (127.0.0.1) 15.44ms
```

**Comment by yuzisun** [comment]
there is new numpy release v1.20.0 which potentially breaks this?

**Comment by PatrickXYS** [comment]
@yuzisun  Thanks for quick fix!
