### ISSUE TITLE
Trained model controller random crash in CI

### ISSUE THREAD

**Issue by yuzisun** [kubeflow/kfserving#1357]
/kind bug

**What steps did you take and what happened:**
```
16026 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 1137 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x17d2f00, 0x26f99a0)
	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/runtime/runtime.go:74 +0xa6
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/runtime/runtime.go:48 +0x89
panic(0x17d2f00, 0x26f99a0)
	/opt/hostedtoolcache/go/1.15.7/x64/src/runtime/panic.go:969 +0x1b9
github.com/kubeflow/kfserving/pkg/controller/v1alpha1/trainedmodel.(*TrainedModelReconciler).updateStatus(0xc00099adc0, 0xc000400c29, 0x7, 0xc000400c10, 0xd, 0xc0006c01c0, 0x14, 0x1bae460)
	/home/runner/work/kfserving/kfserving/pkg/controller/v1alpha1/trainedmodel/controller.go:184 +0x742
github.com/kubeflow/kfserving/pkg/controller/v1alpha1/trainedmodel.(*TrainedModelReconciler).Reconcile(0xc00099adc0, 0xc000400c29, 0x7, 0xc000400c10, 0xd, 0x213b3b0e8, 0xc000686630, 0xc0006865a8, 0xc0006865a0)
	/home/runner/work/kfserving/kfserving/pkg/controller/v1alpha1/trainedmodel/controller.go:126 +0x409
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc0007a2360, 0x1831940, 0xc000f67d80, 0xc000063d00)
	/home/runner/go/pkg/mod/github.com/zchee/sigs.k8s-controller-runtime@v0.6.1-0.20200623114430-46812d3a0a50/pkg/internal/controller/controller.go:233 +0x166
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc0007a2360, 0x203000)
	/home/runner/go/pkg/mod/github.com/zchee/sigs.k8s-controller-runtime@v0.6.1-0.20200623114430-46812d3a0a50/pkg/internal/controller/controller.go:209 +0xb0
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker(0xc0007a2360)
	/home/runner/go/pkg/mod/github.com/zchee/sigs.k8s-controller-runtime@v0.6.1-0.20200623114430-46812d3a0a50/pkg/internal/controller/controller.go:188 +0x2b
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc000d9bd50)
	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:155 +0x5f
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc000d9bd50, 0x1ba6200, 0xc00087c720, 0x1, 0xc000913aa0)
	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:156 +0xad
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000d9bd50, 0x3b9aca00, 0x0, 0x1a81b01, 0xc000913aa0)
	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:133 +0x98
k8s.io/apimachinery/pkg/util/wait.Until(0xc000d9bd50, 0x3b9aca00, 0xc000913aa0)
	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/wait/wait.go:90 +0x4d
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1
	/home/runner/go/pkg/mod/github.com/zchee/sigs.k8s-controller-runtime@v0.6.1-0.20200623114430-46812d3a0a50/pkg/internal/controller/controller.go:170 +0x3fa
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x1675982]

goroutine 1137 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.19.2/pkg/util/runtime/runtime.go:55 +0x10c
panic(0x17d2f00, 0x26f99a0)
	/opt/hostedtoolcache/go/1.15.7/x64/src/runtime/panic.go:969 +0x1b9
github.com/kubeflow/kfserving/pkg/controller/v1alpha1/trainedmodel.(*TrainedModelReconciler).updateStatus(0xc00099adc0, 0xc000400c29, 0x7, 0xc000400c10, 0xd, 0xc0006c01c0, 0x14, 0x1bae460)
	/home/runner/work/kfserving/kfserving/pkg/controller/v1alpha1/trainedmodel/controller.go:184 +0x742
github.com/kubeflow/kfserving/pkg/controller/v1alpha1/trainedmodel.(*TrainedModelReconciler).Reconcile(0xc00099adc0, 0xc000400c29, 0x7, 0xc000400c10, 0xd, 0x213b3b0e8, 0xc000686630, 0xc0006865a8, 0xc0006865a0)
	/home/runner/work/kfserving/kfserving/pkg/controller/v1alpha1/trainedmodel/controller.go:126 +0x409
```	

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Istio Version:
- Knative Version:
- KFServing Version:
- Kubeflow version:
- Kfdef:[k8s_istio/istio_dex/gcp_basic_auth/gcp_iap/aws/aws_cognito/ibm]
- Minikube version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by yuzisun** [comment]
fixed in #1411
