### ISSUE TITLE
[Question] Connecting to gRPC Predictor from Transformer

### ISSUE THREAD

**Issue by markwinter** [kubeflow/kfserving#1420]
I'm currently trying to connect to a gRPC Predictor by creating a channel and stub inside a Transformer

```PYTHON
class BertTransformer(kfserving.KFModel):
    def __init__(self, name: str, predictor_host: str):
        super().__init__(name)

        self.channel = grpc.insecure_channel(predictor_host)
        self.stub = aisp_pb2_grpc.PredictServiceStub(self.channel)

    def preprocess(self, inputs: Dict) -> Dict:
        ...

    def predict(self, features: Dict) -> list:
        ...

        response = self.stub.Predict(request, timeout=10.0)

        ...

    def postprocess(self, result: list) -> Dict:
        ...
```

```YML
apiVersion: "serving.kubeflow.org/v1beta1"
kind: "InferenceService"
metadata:
  name: "sentiment"
spec:
  transformer:
    containers:
      - name: kfserving-container
        image: "deleted"
        command:
          - "python"
          - "-m"
          - "transformer"
  predictor:
    containers:
    - image: "deleted"
      name: kfserving-container
      ports:
        - containerPort: 9000
          name: h2c
          protocol: TCP
      env:
        - name: STORAGE_URI
          value: ""
```

However when trying to send a request, I'm getting 500 internal server error in the Transformer

It seems the grpc client is unable to connect to the Predictor.

```BASH
~ curl -v -H "Host: sentiment.kfserving-test.example.com" http://$IP:$PORT/v1/models/sentiment:predict -d '{"text": "hello"}'
```

```BASH
$ kubectl -n kfserving-test logs sentiment-transformer-default-ggpq5-deployment-6b89589497-l4jcl kfserving-container
[I 210303 07:16:43 kfserver:115] Registering model: sentiment
[I 210303 07:16:43 kfserver:96] Listening on port 8080
[I 210303 07:16:43 kfserver:98] Will fork 1 workers
[E 210303 07:17:16 web:1793] Uncaught exception POST /v1/models/sentiment:predict (127.0.0.1)
    HTTPServerRequest(protocol='http', host='sentiment-transformer-default.kfserving-test.svc.cluster.local', method='POST', uri='/v1/models/sentiment:predict', version='HTTP/1.1', remote_ip='127.0.0.1')
    Traceback (most recent call last):
      File "/usr/local/lib/python3.7/site-packages/tornado/web.py", line 1704, in _execute
        result = await result
      File "/usr/local/lib/python3.7/site-packages/kfserving/handlers/http.py", line 79, in post
        response = (await model.predict(request)) if inspect.iscoroutinefunction(model.predict) else model.predict(request)
      File "/transformer/transformer/bert_transformer.py", line 37, in predict
        response = self.stub.Predict(request, timeout=10.0)
      File "/usr/local/lib/python3.7/site-packages/grpc/_channel.py", line 923, in __call__
        return _end_unary_response_blocking(state, call, False, None)
      File "/usr/local/lib/python3.7/site-packages/grpc/_channel.py", line 826, in _end_unary_response_blocking
        raise _InactiveRpcError(state)
    grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
    	status = StatusCode.UNAVAILABLE
    	details = "failed to connect to all addresses"
    	debug_error_string = "{"created":"@1614755836.012339934","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":5396,"referenced_errors":[{"created":"@1614755836.012338001","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":397,"grpc_status":14}]}"
    >
```

My setup is as follows:
- Minikube v1.16.0
- KFServing 0.5-rc2
- Installed KFServing using ./hack/quick_install.sh

```BASH
$ kubectl -n istio-system get pods
NAME                                    READY   STATUS    RESTARTS   AGE
cluster-local-gateway-d94fc98c6-v25xf   1/1     Running   2          14d
grafana-74dc798895-kspnn                1/1     Running   0          14d
istio-ingressgateway-6f87db8689-mv785   1/1     Running   0          14d
istio-tracing-8584b4d7f9-zbtzk          1/1     Running   0          14d
istiod-6cb5dfb4d6-qsjtn                 1/1     Running   0          14d
kiali-6f457f5964-t4w74                  1/1     Running   0          14d
prometheus-7c9ddc484d-d2wp7             2/2     Running   0          14d
```

Any ideas why the error occurs?

**Comment by markwinter** [comment]
Connecting to the Predictor like this instead worked

```PYTHON
self.channel = grpc.insecure_channel(f"{predictor_host}:80")
```
