### ISSUE TITLE
Error occurs when calling explain in the example of income

### ISSUE THREAD

**Issue by jhs0318** [kubeflow/kfserving#1604]
/kind bug

Hello. I got an error as below while testing the income sample. What could be the problem?
The alibi version is 0.5.5

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
```
│ [I 210429 03:04:05 anchor_tabular:44] Arr shape ((1, 12),)                                                                         │
│ [E 210429 03:04:05 web:1793] Uncaught exception POST /v1/models/income:explain (127.0.0.1)                                 │
│     HTTPServerRequest(protocol='http', host='income-explainer-default.auto-create-26.svc.cluster.local', method='POST', ur │
│ i='/v1/models/income:explain', version='HTTP/1.1', remote_ip='127.0.0.1')                                                  │
│     Traceback (most recent call last):                                                                                             │
│       File "/usr/local/lib/python3.7/site-packages/tornado/web.py", line 1704, in _execute                                         │
│         result = await result                                                                                                      │
│       File "/kfserving/kfserving/handlers/http.py", line 110, in post                                                              │
│         response = (await model.explain(request)) if inspect.iscoroutinefunction(model.explain) else model.explain(request)        │
│       File "/alibiexplainer/alibiexplainer/explainer.py", line 84, in explain                                                      │
│         explanation = self.wrapper.explain(request["instances"])                                                                   │
│       File "/alibiexplainer/alibiexplainer/anchor_tabular.py", line 50, in explain                                                 │
│         self.anchors_tabular.samplers[0].predictor = self.predict_fn                                                               │
│     AttributeError: 'AnchorTabular' object has no attribute 'samplers'                                                             │
│ [E 210429 03:04:05 web:2243] 500 POST /v1/models/income:explain (127.0.0.1) 31.78ms  
```

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Istio Version:
- Knative Version:
- KFServing Version: v0.5.1
- Kubeflow version:
- Kfdef:[k8s_istio/istio_dex/gcp_basic_auth/gcp_iap/aws/aws_cognito/ibm]
- Minikube version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by yuzisun** [comment]
@jhs0318 you must be on some older version of kfserving, this was fixed a while ago https://github.com/kubeflow/kfserving/issues/1088
