### ISSUE TITLE
Predictor downloads model from a HTTPS URI using service account specified whereas explainer does not

### ISSUE THREAD

**Issue by kpulipati** [kubeflow/kfserving#1778]
/kind bug

**What steps did you take and what happened:**
I am trying to deploy a explainer using the below YAML where the storagrUri is a https endpoint where the model and explainer files are hosted:

![image](https://user-images.githubusercontent.com/52773777/130686329-92850709-a9c3-483c-831b-3757781f78dd.png)
The predictor is able to download the model file successfully, but the explainer is unable to download the explainer.dill file using the same service account from the same location.
 Here are the kubernetes pod logs for both predictor and explainer: 
 
**Predictor**: 
 `I0824 13:20:34.826701   32802 request.go:668] Waited for 1.130298993s due to client-side throttling, not priority and fairness, request: GET:https://A1CCAA49C0C4DF1083656F5940B018BB.gr7.us-west-2.eks.amazonaws.com/apis/cache.aws.crossplane.io/v1alpha1?timeout=32s
/usr/local/lib/python3.7/site-packages/ray/autoscaler/_private/cli_logger.py:61: FutureWarning: Not all Ray CLI dependencies were found. In Ray 1.4+, the Ray CLI, autoscaler, and dashboard will only be usable via `pip install 'ray[default]'`. Please update your install command.
  "update your install command.", FutureWarning)
[I 210824 19:30:06 initializer-entrypoint:13] Initializing, args: src_uri [https://artylab.mycompany.com/sample-sklearn-model.pkl?raw=true] dest_path[ [/mnt/models]
[I 210824 19:30:06 storage:50] Copying contents of https://artylab.mycompany.com/sample-sklearn-model.pkl?raw=true to local`
**Explainer (401 error code):** 
`/usr/local/lib/python3.7/site-packages/ray/autoscaler/_private/cli_logger.py:61: FutureWarning: Not all Ray CLI dependencies were found. In Ray 1.4+, the Ray CLI, autoscaler, and dashboard will only be usable via `pip install 'ray[default]'`. Please update your install command.
  "update your install command.", FutureWarning)
[I 210824 19:30:57 initializer-entrypoint:13] Initializing, args: src_uri [https://artylab.mycompany.com/explainer.dill?raw=true] dest_path[ [/mnt/models]
[I 210824 19:30:57 storage:50] Copying contents of https://artylab.mycompany.com/explainer.dill?raw=true to local
Traceback (most recent call last):
  File "/storage-initializer/scripts/initializer-entrypoint", line 14, in <module>
    kfserving.Storage.download(src_uri, dest_path)
  File "/usr/local/lib/python3.7/site-packages/kfserving/storage.py", line 73, in download
    return Storage._download_from_uri(uri, out_dir)
  File "/usr/local/lib/python3.7/site-packages/kfserving/storage.py", line 270, in _download_from_uri
    raise RuntimeError("URI: %s returned a %s response code." % (uri, response.status_code))
RuntimeError: URI: https://artylab.mycompany.com/explainer.dill?raw=true returned a 401 response code.`
**What did you expect to happen:**

The explainer pods should be able to download the file successfully.
**Anything else you would like to add:**

I pointed the predictor pod to download the explainer file instead of the model file and it worked fine. But somehow the explainer pod is not able to download anything.

**Environment:**

- Istio Version:
- Knative Version: v0.24.0
- KFServing Version:
- Kubeflow version:
- Kfdef:[k8s_istio/istio_dex/gcp_basic_auth/gcp_iap/aws/aws_cognito/ibm]
- Minikube version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by kpulipati** [comment]
@yuzisun Hi Dan, could you please confirm if this is a known bug in case you are aware of it?
