### ISSUE TITLE
Will the model be reloaded after isvc is released for a period of time?

### ISSUE THREAD

**Issue by SeibertronSS** [kubeflow/kfserving#1784]
Hello everyone,
I find that isvc will reload the model after a period of time, which will cause my pod status to `Init:CrashLoopBackOff`, the error message is as follows,

```
Traceback (most recent call last):
  File "/storage-initializer/scripts/initializer-entrypoint", line 14, in <module>
    kfserving.Storage.download(src_uri, dest_path)
  File "/usr/local/lib/python3.7/site-packages/kfserving/storage.py", line 66, in download
    return Storage._download_local(uri, out_dir)
  File "/usr/local/lib/python3.7/site-packages/kfserving/storage.py", line 224, in _download_local
    os.symlink(src, dest_path)
FileExistsError: [Errno 17] File exists: '/mnt/pvc/workspace/model/flower102/deploy/model.pt' -> '/mnt/models/model.pt'
```
Is there a way to prevent isvc from reloading the model?

**Comment by yuzisun** [comment]
@SeibertronSS Isvc does not reload the model unless your pod gets restarted.
