### ISSUE TITLE
support minio service

### ISSUE THREAD

**Issue by hwk42** [kubeflow/kfserving#1793]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
I follow the [example](https://github.com/kubeflow/kfserving/tree/v0.5.1/docs/samples/storage/s3),with minio buildin in kubeflow instead of aws s3，it occur err with log:
`[I 210907 03:40:05 storage:45] Copying contents of s3://test/cifar10 to local
Traceback (most recent call last):
  File "/storage-initializer/scripts/initializer-entrypoint", line 14, in <module>
    kfserving.Storage.download(src_uri, dest_path)
  File "/usr/local/lib/python3.7/site-packages/kfserving/storage.py", line 62, in download
    Storage._download_s3(uri, out_dir)
  File "/usr/local/lib/python3.7/site-packages/kfserving/storage.py", line 89, in _download_s3
    for obj in objects:
  File "/usr/local/lib/python3.7/site-packages/minio/api.py", line 2297, in _list_objects
    query=query,
  File "/usr/local/lib/python3.7/site-packages/minio/api.py", line 2229, in _url_open
    object_name).get_exception()
minio.error.AccessDenied: AccessDenied: message: Access Denied`

**What did you expect to happen:**
support minio service

**Anything else you would like to add:**

As notice this [issue](https://github.com/kubeflow/pipelines/issues/5700), is it also because minio dosen't support sa? If yes,any idea or plan to deal with minio?

**Environment:**
- KFServing Version: 0.5.1
- Kubeflow version: 1.3

**Comment by tdnguyen6** [comment]
Where did you find that log? Did you manage to resolve it?

**Comment by hwk42** [comment]
I found that log in the `storage-initializer`container.And I upgrade to v0.6.1,it works with sa.Thanks for help.
