### ISSUE TITLE
How can I manage the addition / removal of TorchServe models?

### ISSUE THREAD

**Issue by yurkoff-mv** [kubeflow/kfserving#1798]
TorchServe has the ability to add and remove models with the following commands:
`curl -X POST  "http://localhost:8081/models?url=my_model.mar&model_name=my_model&initial_workers=1&synchronous=false&number_gpu=1"`
and
`curl -X DELETE  "http://localhost:8081/models/my_model"`
Is there such a possibility in the KFServing?

If you do not write a snapshot in the file `config.properties` during deployment, the following error is generated:
`!kubectl logs -n default my-model-predictor-default-9vctz-deployment-575566b77cdqtp2  -c kfserving-container`

```
Traceback (most recent call last):
  File "/serve/kubernetes/kfserving/kfserving_wrapper/__main__.py", line 75, in <module>
    model_names, inference_address, management_address, model_dir = parse_config()
  File "/serve/kubernetes/kfserving/kfserving_wrapper/__main__.py", line 43, in parse_config
    keys["model_snapshot"] = json.loads(keys["model_snapshot"])
KeyError: 'model_snapshot'
```

**Comment by yurkoff-mv** [comment]
And one more question. How can I use a gRPC for management models and implementation of predictions.?

**Comment by yurkoff-mv** [comment]
Regarding the gRPC protocol, I created InferenceService:
```
port_inference = client.V1ContainerPort(7070, protocol='TCP', name='h2c')

pytorch_predictor=V1beta1PredictorSpec(
    pytorch=V1beta1TorchServeSpec(
        storage_uri='pvc://torchserve-pv-claim/torchserve',
        resources=V1ResourceRequirements(requests={'cpu':'1000m', 'memory':'4Gi', 'nvidia.com/gpu': '1'},
                                         limits={'cpu':'1000m', 'memory':'8Gi', 'nvidia.com/gpu': '1'}),
        ports=[port_inference]
    )
)

isvc = V1beta1InferenceService(api_version=constants.KFSERVING_V1BETA1,
                               kind=constants.KFSERVING_KIND,
                               metadata=client.V1ObjectMeta(name=model_name, namespace=namespace),
                               spec=V1beta1InferenceServiceSpec(predictor=pytorch_predictor))
```
But it not works with gRPC. My code:
```
def get_inference_stub(host, port, hostname):
    if hostname:
        host_option = (('grpc.ssl_target_name_override', hostname,))
    else:
        host_option =  None
    channel = grpc.insecure_channel(target='{host}:{port}'.format(host=host, port=port), options=host_option)
    stub = inference_pb2_grpc.InferenceAPIsServiceStub(channel)
    return stub

def ping(stub):
    response = stub.Ping(empty_pb2.Empty())
    try:
        return response.health
    except grpc.RpcError as e:
        exit(1)

def infer(stub, model_name, data):
    input_data = {'data': data}
    response = stub.Predictions(inference_pb2.PredictionsRequest(model_name=model_name, input=input_data))
    try:
        data = response.prediction
        return data
    except grpc.RpcError as e:
        exit(1)

#ping(get_inference_stub(INGRESS_HOST, INGRESS_PORT, SERVICE_HOSTNAME))
response = infer(get_inference_stub(INGRESS_HOST, INGRESS_PORT, SERVICE_HOSTNAME), "my-model", data)
```
Error:
```
/opt/conda/lib/python3.8/site-packages/grpc/_channel.py in _end_unary_response_blocking(state, call, with_call, deadline)
    847             return state.response
    848     else:
--> 849         raise _InactiveRpcError(state)
    850 
    851 

_InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNKNOWN
	details = ""
	debug_error_string = "{"created":"@1631636547.834246092","description":"Error received from peer ipv4:10.152.183.93:80","file":"src/core/lib/surface/call.cc","file_line":1069,"grpc_message":"","grpc_status":2}"
```
Where:
MODEL_NAME=my-model
```
INGRESS_HOST = !kubectl -n istio-system get service istio-ingressgateway -o jsonpath='{.spec.clusterIP}' 
INGRESS_PORT = !kubectl -n istio-system get service istio-ingressgateway -o jsonpath='{.spec.ports[?(@.name=="http2")].port}'
SERVICE_HOSTNAME=$(kubectl get inferenceservice ${MODEL_NAME} -o jsonpath='{.status.url}' | cut -d "/" -f 3)
```
```
print(INGRESS_PORT)
80
```

**Comment by jagadeeshi2i** [comment]
@yurkoff-mv Currently Torhcserve KFServing does not support model management via REST APIs. 

For gRPC, there a PR in progress.  #1747. Refer readme and gRPC client..
