### ISSUE TITLE
Model initializer does not work with S3

### ISSUE THREAD

**Issue by yuzisun** [kubeflow/kfserving#213]
/kind bug

**What steps did you take and what happened:**
The model download is now moved to `init container`, however the S3 secret envs are set in the `user-container`. 

kubectl logs mnist-default-g7px9-deployment-5d6d7f897c-t5rzk -c model-initializer 
INFO:root:Initializing, args: src_uri [s3://platform-test/mnist/export] dest_path[ [/mnt/models]
INFO:root:Copying contents of s3://platform-test/mnist/export to local
Traceback (most recent call last):
  File "/model-initializer/scripts/initializer-entrypoint", line 14, in <module>
    kfserving.Storage.download(src_uri, dest_path)
  File "/kfserving/kfserving/storage.py", line 41, in download
    Storage._download_s3(uri, out_dir)
  File "/kfserving/kfserving/storage.py", line 52, in _download_s3
    client = Storage._create_minio_client()
  File "/kfserving/kfserving/storage.py", line 105, in _create_minio_client
    secure=True)
  File "/usr/local/lib/python3.7/site-packages/minio/api.py", line 149, in __init__
    is_valid_endpoint(endpoint)
  File "/usr/local/lib/python3.7/site-packages/minio/helpers.py", line 301, in is_valid_endpoint
    if hostname[-1] == '.':
IndexError: string index out of range

**What did you expect to happen:**
Secret env and mount should be moved to init container.

**Comment by rakelkar** [comment]
/assign rakelkar
taking a look...

**Comment by Tomcli** [comment]
Hi @rakelkar, I'm also having this issue with S3 using KFServing v0.2. I tested with the S3 example from the doc using minio and also have the same problem. Do you have any solution on this? Thanks. 

Below are my storage-initializer logs
```
INFO:root:Initializing, args: src_uri [s3://mnist-test/] dest_path[ [/mnt/models]
INFO:root:Copying contents of s3://mnist-test/ to local
Traceback (most recent call last):
  File "/storage-initializer/scripts/initializer-entrypoint", line 14, in <module>
    kfserving.Storage.download(src_uri, dest_path)
  File "/usr/local/lib/python3.7/site-packages/kfserving/storage.py", line 51, in download
    Storage._download_s3(uri, out_dir)
  File "/usr/local/lib/python3.7/site-packages/kfserving/storage.py", line 66, in _download_s3
    client = Storage._create_minio_client()
  File "/usr/local/lib/python3.7/site-packages/kfserving/storage.py", line 204, in _create_minio_client
    secure=use_ssl)
  File "/usr/local/lib/python3.7/site-packages/minio/api.py", line 150, in __init__
    is_valid_endpoint(endpoint)
  File "/usr/local/lib/python3.7/site-packages/minio/helpers.py", line 301, in is_valid_endpoint
    if hostname[-1] == '.':
IndexError: string index out of range
```

**Comment by yuzisun** [comment]
@Tomcli that's probably setup issue, we internally installed 0.2 and also use S3 all working fine. Can you paste the output of the inferenceservice pod yaml here?
