### ISSUE TITLE
explainer never becomes available in 0.2.0

### ISSUE THREAD

**Issue by ryandawsonuk** [kubeflow/kfserving#483]
Installed using kfctl, currently pointed at 0.2.0. Ran through https://github.com/kubeflow/kfserving/tree/master/docs/samples/explanation/alibi/income

Operator errors with:
```
usr/local/go/src/runtime/asm_amd64.s:2361
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x58 pc=0x102d61f]

goroutine 160 [running]:
github.com/kubeflow/kfserving/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
        /go/src/github.com/kubeflow/kfserving/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:58 +0x107
panic(0x125ef40, 0x1d7ea00)
        /usr/local/go/src/runtime/panic.go:502 +0x229
github.com/kubeflow/kfserving/pkg/controller/inferenceservice/resources/istio.getExplainStatusConfigurationSpec(...)
        /go/src/github.com/kubeflow/kfserving/pkg/controller/inferenceservice/resources/istio/virtualservice.go:241
github.com/kubeflow/kfserving/pkg/controller/inferenceservice/resources/istio.(*VirtualServiceBuilder).CreateVirtualService(0xc420de6410, 0xc420190d20, 0xc4219e1ba8, 0x1036e30)
        /go/src/github.com/kubeflow/kfserving/pkg/controller/inferenceservice/resources/istio/virtualservice.go:156 +0xbef
github.com/kubeflow/kfserving/pkg/controller/inferenceservice/reconcilers/istio.(*VirtualServiceReconciler).Reconcile(0xc420135160, 0xc420190d20, 0x0, 0x0)
        /go/src/github.com/kubeflow/kfserving/pkg/controller/inferenceservice/reconcilers/istio/virtualservice_reconciler.go:54 +0x3d
github.com/kubeflow/kfserving/pkg/controller/inferenceservice.(*ReconcileService).Reconcile(0xc4208361b0, 0xc42057b149, 0x7, 0xc42057b134, 0x6, 0x1d92e40, 0x0, 0x0, 0x0)
        /go/src/github.com/kubeflow/kfserving/pkg/controller/inferenceservice/controller.go:146 +0x46b
```
So status is reported as not ready. But kservice actually is ready and pods are created

**Comment by cliveseldon** [comment]
This works for me on master. I think we need to push updates into 0.2.0 @ellis-bigelow for kubeflow

**Comment by yuzisun** [comment]
this has been fixed in https://github.com/kubeflow/kfserving/pull/446.

**Comment by yuzisun** [comment]
image gcr.io/kfserving/alibi-explainer:0.2.0 is updated.
/close
