### ISSUE TITLE
storage_initializer.download_local

### ISSUE THREAD

**Issue by Iamlovingit** [kubeflow/kfserving#567]
/kind bug

**What steps did you take and what happened:**
[A clear and concise description of what the bug is.]
when using storage download local model. The `_download_local` fucntion creates a soft-link, this will lead to pytorchservr/tfserving can not correctly load the model(can not open).  
https://github.com/kubeflow/kfserving/blob/c3aeced18f1c5a011b277d3fab42d1e81c478fa8/python/kfserving/kfserving/storage.py#L206
a copy option can solve it.
`so.system("cp -rp {} {}".format(src,dest_path))`
**What did you expect to happen:**
server can load model

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Istio Version:
- Knative Version:
- KFServing Version:
- Kubeflow version:
- Minikube version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by ellis-bigelow** [comment]
Thanks for the report. Huge bummer. Assigning to @rakelkar who owns this code.

**Comment by pugangxa** [comment]
How do you do your test? To prove copy option work you must rebuild the storage initializer and specify  it in your configmap. 
I remember I tried it before and it works, and checked seems no breaking changes these days. Also make sure you must follow the steps to create pv and then specify the path correctly. The local download only works for the pv and since the model already mounted the pv the symbolic link should work.

**Comment by Iamlovingit** [comment]
> How do you do your test? To prove copy option work you must rebuild the storage initializer and specify  it in your configmap.
> I remember I tried it before and it works, and checked seems no breaking changes these days. Also make sure you must follow the steps to create pv and then specify the path correctly. The local download only works for the pv and since the model already mounted the pv the symbolic link should work.

I modify the storage initializer dockerfile, add local cifar10 to image. Then rebuild the image and modify the configmap. At last deploy the kfserving by command `make manifest & make deploy-dev`. The container ` kfserving-container` can not load the model file correct.

**Comment by ellis-bigelow** [comment]
Do you have any logs?

**Comment by Iamlovingit** [comment]
> Do you have any logs?

sorry for late reply. iill show my dockerfile, and wrong msg below:
* add  `copy` to dockerfile.
**storage_initailizer dockerfile:**
```
FROM python:3.7-slim

COPY ./kfserving ./kfserving
RUN pip install --upgrade pip && pip install ./kfserving

COPY ./storage-initializer /storage-initializer
RUN chmod +x /storage-initializer/scripts/initializer-entrypoint

RUN mkdir /cifar10
WORKDIR /cifar10
COPY ./cifar10 .

RUN mkdir /work
WORKDIR /work
ENTRYPOINT ["/storage-initializer/scripts/initializer-entrypoint"]
```
* rebuild the storage image. and the modify the config map.
`config/default/configmap/inferenceservice.yaml`
```
storageInitializer: |-
    {
        "image" : "10.166.15.29:5000/gcr.io/kfserving/my-storage-initializer:test12",
        "memoryRequest": "100Mi",
        "memoryLimit": "1Gi",
        "cpuRequest": "100m",
        "cpuLimit": "1"
    }
```

* modify the pytorch sample storage uri to 'local'
**pytorch.yaml**
```
apiVersion: serving.kubeflow.org/v1alpha2
kind: InferenceService
metadata:
  name: "pytorch-cifar10"
spec:
  default:
    predictor:
      pytorch:
        #storageUri: "gs://kfserving-samples/models/pytorch/cifar10/"
        storageUri: "file:///cifar10/"
        modelClassName: "Net"
```

* deploy kfserving
`make mainifest &make  deploy-dev`

*  wrong mes , run `kubectl describe pod podname`
```
INFO:root:model_class_file=/mnt/models/mycifar10.py
Traceback (most recent call last):
  File "/opt/conda/envs/pytorch-py37/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/conda/envs/pytorch-py37/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/workspace/pytorchserver/pytorchserver/__main__.py", line 35, in <module>
    model.load()
  File "/workspace/pytorchserver/pytorchserver/model.py", line 71, in load
    with open(model_class_file, 'r', encoding='utf-8') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/models/mycifar10.py'
```
pytorchserver can list the `mycifar10.py`, but can't open it.
the reason is,  **storage container**  create a soft link to `/mnt/models/`, `/mnt/models`  is a share dircetory. actually, the file obj is in directory `/cifar10` . so the **pytorchserver container** can not open it.
the whole `describe`
```
root@k8s-master:kfserving# kubectl describe pod pytorch-cifar10-predictor-default-qn8lk-deployment-56c77bfd2rmk
Name:               pytorch-cifar10-predictor-default-qn8lk-deployment-56c77bfd2rmk
Namespace:          default
Priority:           0
PriorityClassName:  <none>
Node:               k8s-node1/10.166.15.37
Start Time:         Sat, 14 Dec 2019 15:07:56 +0800
Labels:             app=pytorch-cifar10-predictor-default-qn8lk
                    pod-template-hash=56c77bf589
                    serving.knative.dev/configuration=pytorch-cifar10-predictor-default
                    serving.knative.dev/configurationGeneration=1
                    serving.knative.dev/revision=pytorch-cifar10-predictor-default-qn8lk
                    serving.knative.dev/revisionUID=7449ed48-1e40-11ea-8f5b-6c92bf8639ac
                    serving.knative.dev/service=pytorch-cifar10-predictor-default
                    serving.kubeflow.org/inferenceservice=pytorch-cifar10
Annotations:        autoscaling.knative.dev/class: kpa.autoscaling.knative.dev
                    autoscaling.knative.dev/target: 1
                    cni.projectcalico.org/podIP: 192.168.36.151/32
                    internal.serving.kubeflow.org/storage-initializer-sourceuri: file:///cifar10/
                    queue.sidecar.serving.knative.dev/resourcePercentage: 0.2
                    serving.knative.dev/creator: system:serviceaccount:kfserving-system:default
                    sidecar.istio.io/inject: true
                    traffic.sidecar.istio.io/includeOutboundIPRanges: *
Status:             Running
IP:                 192.168.36.151
Controlled By:      ReplicaSet/pytorch-cifar10-predictor-default-qn8lk-deployment-56c77bf589
Init Containers:
  storage-initializer:
    Container ID:  docker://b65bf74f6244a88791c99ba43cb0287aaae61c3cd41e7028ce14d379933a8ffb
    Image:         10.166.15.29:5000/storage-initializer:test13
    Image ID:      docker-pullable://10.166.15.29:5000/storage-initializer@sha256:108e6b0c33fc282fbb328d9f5d11b9d64c76d236e0f01e96ce95d1241a0ba251
    Port:          <none>
    Host Port:     <none>
    Args:
      file:///cifar10/
      /mnt/models
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Sat, 14 Dec 2019 15:07:58 +0800
      Finished:     Sat, 14 Dec 2019 15:07:59 +0800
    Ready:          True
    Restart Count:  0
    Limits:
      cpu:     1
      memory:  1Gi
    Requests:
      cpu:        100m
      memory:     100Mi
    Environment:  <none>
    Mounts:
      /mnt/models from kfserving-provision-location (rw)
Containers:
  kfserving-container:
    Container ID:  docker://4af6f1a990615079affbe257a51af398a9c5e46640ce4bf33a576d540ea8b803
    Image:         10.166.15.29:5000/gcr.io/kfserving/pytorchserver@sha256:63b8aeae602d1e5cd90da66db1524c2e7b1e3a2cca7dacecebc327e82150aa5c
    Image ID:      docker-pullable://10.166.15.29:5000/gcr.io/kfserving/pytorchserver@sha256:63b8aeae602d1e5cd90da66db1524c2e7b1e3a2cca7dacecebc327e82150aa5c
    Port:          8080/TCP
    Host Port:     0/TCP
    Args:
      --model_name=pytorch-cifar10
      --model_class_name=Net
      --model_dir=/mnt/models
    State:       Waiting
      Reason:    CrashLoopBackOff
    Last State:  Terminated
      Reason:    Error
      Message:   erfile]
INFO:root:aaa dir=[/workspace], filename=[Running]
INFO:root:aaa dir=[/workspace], filename=[storage-initializer]
INFO:root:aaa dir=[/workspace], filename=[.pylintrc]
INFO:root:aaa dir=[/workspace], filename=[flowers-2]
INFO:root:aaa dir=[/workspace], filename=[pytorchserver.Dockerfile]
INFO:root:aaa dir=[/workspace], filename=[alibiexplainer.Dockerfile]
INFO:root:aaa dir=[/workspace], filename=[tensorrt]
INFO:root:aaa dir=[/workspace], filename=[cifar10-resnet]
INFO:root:aaa dir=[/workspace], filename=[4a4c7fe74295]
INFO:root:aaa dir=[/workspace], filename=[cifar10]
INFO:root:aaa dir=[/workspace], filename=[sklearn.Dockerfile]
INFO:root:aaa dir=[/workspace], filename=[.gitignore]
INFO:root:000 dir=[/mnt/models], filename=[mycifar10.py]
INFO:root:000 dir=[/mnt/models], filename=[model.pt]
INFO:root:Copying contents of /mnt/models to local
INFO:root:111 dir=[/mnt/models], filename=[mycifar10.py]
INFO:root:111 dir=[/mnt/models], filename=[model.pt]
INFO:root:cqs test ...  down load ok, model_file= [/mnt/models/model.pt]
INFO:root:222 dir=[/mnt/models], filename=[mycifar10.py]
INFO:root:222 dir=[/mnt/models], filename=[model.pt]
INFO:root:dir=[/mnt/models], filename=[mycifar10.py]
INFO:root:append mycifar10.py, py_files.len=1
INFO:root:dir=[/mnt/models], filename=[model.pt]
INFO:root:444 dir=[/mnt/models], filename=[mycifar10.py]
INFO:root:444 dir=[/mnt/models], filename=[model.pt]
INFO:root:model_class_file=/mnt/models/mycifar10.py
Traceback (most recent call last):
  File "/opt/conda/envs/pytorch-py37/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/conda/envs/pytorch-py37/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/workspace/pytorchserver/pytorchserver/__main__.py", line 35, in <module>
    model.load()
  File "/workspace/pytorchserver/pytorchserver/model.py", line 71, in load
    with open(model_class_file, 'r', encoding='utf-8') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/models/mycifar10.py'

      Exit Code:    1
      Started:      Sat, 14 Dec 2019 15:29:25 +0800
      Finished:     Sat, 14 Dec 2019 15:29:26 +0800
    Ready:          False
    Restart Count:  9
    Limits:
      cpu:     1
      memory:  2Gi
    Requests:
      cpu:     1
      memory:  2Gi
    Environment:
      PORT:             8080
      K_REVISION:       pytorch-cifar10-predictor-default-qn8lk
      K_CONFIGURATION:  pytorch-cifar10-predictor-default
      K_SERVICE:        pytorch-cifar10-predictor-default
    Mounts:
      /mnt/models from kfserving-provision-location (ro)
      /var/log from knative-var-log (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-6w5tt (ro)
  queue-proxy:
    Container ID:   docker://a0e9804f22a27f43e840ce5b31be19308b1b26b80cc0945d31cd7be96e518618
    Image:          iamlovingit/knative-v0.10-serving-queue:latest
    Image ID:       docker-pullable://iamlovingit/knative-v0.10-serving-queue@sha256:b20c6a626789f25922f2d86a0f460327d5053776f736fc67c7fd7687d2bcc294
    Ports:          8022/TCP, 9090/TCP, 9091/TCP, 8012/TCP
    Host Ports:     0/TCP, 0/TCP, 0/TCP, 0/TCP
    State:          Running
      Started:      Sat, 14 Dec 2019 15:08:04 +0800
    Ready:          False
    Restart Count:  0
    Limits:
      cpu:     40m
      memory:  200Mi
    Requests:
      cpu:      25m
      memory:   50Mi
    Readiness:  exec [/ko-app/queue -probe-period 0] delay=0s timeout=10s period=1s #success=1 #failure=3
    Environment:
      SERVING_NAMESPACE:                      default
      SERVING_SERVICE:                        pytorch-cifar10-predictor-default
      SERVING_CONFIGURATION:                  pytorch-cifar10-predictor-default
      SERVING_REVISION:                       pytorch-cifar10-predictor-default-qn8lk
      QUEUE_SERVING_PORT:                     8012
      CONTAINER_CONCURRENCY:                  0
      REVISION_TIMEOUT_SECONDS:               60
      SERVING_POD:                            pytorch-cifar10-predictor-default-qn8lk-deployment-56c77bfd2rmk (v1:metadata.name)
      SERVING_POD_IP:                          (v1:status.podIP)
      SERVING_LOGGING_CONFIG:                 {
                                                "level": "info",
                                                "development": false,
                                                "outputPaths": ["stdout"],
                                                "errorOutputPaths": ["stderr"],
                                                "encoding": "json",
                                                "encoderConfig": {
                                                  "timeKey": "ts",
                                                  "levelKey": "level",
                                                  "nameKey": "logger",
                                                  "callerKey": "caller",
                                                  "messageKey": "msg",
                                                  "stacktraceKey": "stacktrace",
                                                  "lineEnding": "",
                                                  "levelEncoder": "",
                                                  "timeEncoder": "iso8601",
                                                  "durationEncoder": "",
                                                  "callerEncoder": ""
                                                }
                                              }
      SERVING_LOGGING_LEVEL:                  
      SERVING_REQUEST_LOG_TEMPLATE:           
      SERVING_REQUEST_METRICS_BACKEND:        
      TRACING_CONFIG_BACKEND:                 none
      TRACING_CONFIG_ZIPKIN_ENDPOINT:         
      TRACING_CONFIG_STACKDRIVER_PROJECT_ID:  
      TRACING_CONFIG_DEBUG:                   false
      TRACING_CONFIG_SAMPLE_RATE:             0.100000
      USER_PORT:                              8080
      SYSTEM_NAMESPACE:                       knative-serving
      METRICS_DOMAIN:                         knative.dev/internal/serving
      USER_CONTAINER_NAME:                    kfserving-container
      ENABLE_VAR_LOG_COLLECTION:              false
      VAR_LOG_VOLUME_NAME:                    knative-var-log
      INTERNAL_VOLUME_PATH:                   /var/knative-internal
      SERVING_READINESS_PROBE:                {"tcpSocket":{"port":8080,"host":"127.0.0.1"},"successThreshold":1}
      ENABLE_PROFILING:                       false
      SERVING_ENABLE_PROBE_REQUEST_LOG:       false
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-6w5tt (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  knative-var-log:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
  default-token-6w5tt:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-6w5tt
    Optional:    false
  kfserving-provision-location:
    Type:        EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:      
    SizeLimit:   <unset>
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason     Age                   From                Message
  ----     ------     ----                  ----                -------
  Normal   Scheduled  23m                   default-scheduler   Successfully assigned default/pytorch-cifar10-predictor-default-qn8lk-deployment-56c77bfd2rmk to k8s-node1
  Normal   Pulled     23m                   kubelet, k8s-node1  Container image "10.166.15.29:5000/storage-initializer:test13" already present on machine
  Normal   Created    23m                   kubelet, k8s-node1  Created container storage-initializer
  Normal   Started    23m                   kubelet, k8s-node1  Started container storage-initializer
  Normal   Pulling    23m                   kubelet, k8s-node1  Pulling image "iamlovingit/knative-v0.10-serving-queue:latest"
  Normal   Created    23m                   kubelet, k8s-node1  Created container queue-proxy
  Normal   Pulled     23m                   kubelet, k8s-node1  Successfully pulled image "iamlovingit/knative-v0.10-serving-queue:latest"
  Normal   Started    23m                   kubelet, k8s-node1  Started container queue-proxy
  Normal   Created    23m (x3 over 23m)     kubelet, k8s-node1  Created container kfserving-container
  Normal   Started    23m (x3 over 23m)     kubelet, k8s-node1  Started container kfserving-container
  Normal   Pulled     23m (x4 over 23m)     kubelet, k8s-node1  Container image "10.166.15.29:5000/gcr.io/kfserving/pytorchserver@sha256:63b8aeae602d1e5cd90da66db1524c2e7b1e3a2cca7dacecebc327e82150aa5c" already present on machine
  Warning  Unhealthy  8m55s (x78 over 23m)  kubelet, k8s-node1  Readiness probe failed: probe returned not ready
  Warning  BackOff    3m46s (x94 over 23m)  kubelet, k8s-node1  Back-off restarting failed container
```
