### ISSUE TITLE
104 Connection Refused on large transformation request

### ISSUE THREAD

**Issue by alexwennerberg** [kubeflow/kfserving#633]
/kind bug

I'm deploying a Pytorch model that takes as input an image URI from Google Cloud Storage, runs through the KFServing preprocess function to load the image file as a tensor, then makes the request to the predictor. This is very similar to https://github.com/kubeflow/kfserving/tree/master/docs/samples/transformer/image_transformer -- almost identical, the only relevant difference being the size of the input tensor.

I am loading a 4K image, and after the image tensor is serialized as a JSON, it is about 21MB. 

When I connect to the prediction server directly, I am able to send the request just fine. I have tried running the request both from the transformation container and my local computer and haven't had an issue. However, when the request is made from the Tornado server in the transformation container, it gets a 104 Connection Refused error from the prediction server.

When I open a debugger and make a much smaller request in the server thread, it doesn't give me this error.

Is this a bug or some sort of undocumented limit? I could not find anything in a cursory search in Tornado, Requests, or KFserving about limits on large request sizes. Thanks!

Here is the full traceback from the transformation container:

```
    Traceback (most recent call last):                    
      File "/usr/local/lib/python3.7/site-packages/tornado/web.py", line 1697, in _execute                                                                                  
        result = method(*self.path_args, **self.path_kwargs)          
      File "/usr/local/lib/python3.7/site-packages/kfserving/handlers/http.py", line 51, in post                                                                            
        response = model.predict(request)                   
      File "/usr/local/lib/python3.7/site-packages/kfserving/kfmodel.py", line 49, in predict                                                                               
        PREDICTOR_URL_FORMAT.format(self.predictor_host, self.name),  
      File "/usr/local/lib/python3.7/site-packages/requests/api.py", line 116, in post
        return request('post', url, data=data, json=json, **kwargs)   
      File "/usr/local/lib/python3.7/site-packages/requests/api.py", line 60, in request                                                                                    
        return session.request(method=method, url=url, **kwargs)
      File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 533, in request                                                                              
        resp = self.send(prep, **send_kwargs)                         
      File "/usr/local/lib/python3.7/site-packages/requests/sessions.py", line 646, in send                                                                                 
        r = adapter.send(request, **kwargs)
      File "/usr/local/lib/python3.7/site-packages/requests/adapters.py", line 498, in send                                                                                 
        raise ConnectionError(err, request=request)                                        
    requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer')) 
```

**Environment:**

- Istio Version: 1.2.10-gke.0
- Knative Version: 0.11.0
- KFServing Version: 0.2.2
- Kubeflow version: (Not used)
- Kubernetes version: v1.15.7-gke.2 (Google Kubernetes Engine)

**Comment by alexwennerberg** [comment]
Should be resolved by https://github.com/kubeflow/kfserving/pull/665/commits -- I'll verify a fix if I have a chance
