### ISSUE TITLE
xgbserver build is broken

### ISSUE THREAD

**Issue by yuzisun** [kubeflow/kfserving#639]
/kind bug

**What steps did you take and what happened:**
Not sure what changed but xgbserver docker build is broken, can easily replicate locally also
`docker build -t test -f xgb.Dockerfile . --rm`

```
    ERROR: Command errored out with exit status 1:
     command: /usr/local/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-310wkr6l/xgboost/setup.py'"'"'; __file__='"'"'/tmp/pip-install-310wkr6l/xgboost/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-310wkr6l/xgboost/pip-egg-info
         cwd: /tmp/pip-install-310wkr6l/xgboost/
    Complete output (20 lines):
    + pwd
    + oldpath=/tmp/pip-install-310wkr6l/xgboost
    + cd ./xgboost/
    + echo
    + grep -q darwin
    + LIB_XGBOOST=libxgboost.so
    + make clean
    ./xgboost/build-python.sh: 40: ./xgboost/build-python.sh: make: not found
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-310wkr6l/xgboost/setup.py", line 42, in <module>
        LIB_PATH = libpath['find_lib_path']()
      File "/tmp/pip-install-310wkr6l/xgboost/xgboost/libpath.py", line 49, in find_lib_path
        'List of candidates:\n' + ('\n'.join(dll_path)))
    XGBoostLibraryNotFound: Cannot find XGBoost Library in the candidate path, did you install compilers and run build.sh in root path?
    List of candidates:
    /tmp/pip-install-310wkr6l/xgboost/xgboost/libxgboost.so
    /tmp/pip-install-310wkr6l/xgboost/xgboost/../../lib/libxgboost.so
    /tmp/pip-install-310wkr6l/xgboost/xgboost/./lib/libxgboost.so
    /usr/local/xgboost/libxgboost.so
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Istio Version:
- Knative Version:
- KFServing Version: master
- Kubeflow version:
- Minikube version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

**Comment by yuzisun** [comment]
looks like new version of pip caused this issue: https://github.com/dmlc/xgboost/issues/5221
