### ISSUE TITLE
Dynamic container construction to mitigate InferenceService Python dependency issues

### ISSUE THREAD

**Issue by jpatanooga** [kubeflow/kfserving#830]
/kind feature

**Describe the solution you'd like**

Currently there are issues where if a model was not built with the same versions of dependencies baked into the InferenceService model server container images, then the InferenceService will fail post-deploy during inference execution.

A typical error code:

kfserving-container:
    Container ID:  docker://e32e4a84a9de06f12af7c05bcc469958de43dbb60c95651f64ee0e407e157f42
    Image:         gcr.io/kfserving/sklearnserver@sha256:6702dddff99de5b8945f35d913a423e406b6cd039a14cefdbd1886078d393ce5
    Image ID:      docker-pullable://gcr.io/kfserving/sklearnserver@sha256:6702dddff99de5b8945f35d913a423e406b6cd039a14cefdbd1886078d393ce5
    Port:          8080/TCP
    Host Port:     0/TCP
    Args:
      --model_name=aws-sklearn-model
      --model_dir=/mnt/models
      --http_port=8080
    State:       Waiting
      Reason:    CrashLoopBackOff
    Last State:  Terminated
      Reason:    Error
      Message:   [I 200516 20:20:16 storage:35] Copying contents of /mnt/models to local
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/sklearnserver/sklearnserver/__main__.py", line 33, in <module>
    model.load()
  File "/sklearnserver/sklearnserver/model.py", line 32, in load
    self._joblib = joblib.load(model_file) #pylint:disable=attribute-defined-outside-init
  File "/usr/local/lib/python3.7/site-packages/joblib/numpy_pickle.py", line 605, in load
    obj = _unpickle(fobj, filename, mmap_mode)
  File "/usr/local/lib/python3.7/site-packages/joblib/numpy_pickle.py", line 529, in _unpickle
    obj = unpickler.load()
  File "/usr/local/lib/python3.7/pickle.py", line 1088, in load
    dispatch[key[0]](self)
  File "/usr/local/lib/python3.7/pickle.py", line 1376, in load_global
    klass = self.find_class(module, name)
  File "/usr/local/lib/python3.7/pickle.py", line 1426, in find_class
    __import__(module, level=0)
ModuleNotFoundError: No module named 'sklearn.svm._classes'

To get around this, currently we have to either:

(1) manually check:

https://github.com/kubeflow/kfserving/blob/master/config/default/configmap/inferenceservice.yaml#L9

and then make sure our model was built with the same dependency versions

(2) build a custom inference service image manually

This feature enhancement request proposes that KFServing adopt a dynamic image building execution path such that the system allows use to specify dependency versions in the resource yaml. An example of this yaml is shown below:

apiVersion: "serving.kubeflow.org/v1alpha2"
kind: "InferenceService"
metadata:
  name: "sklearn-iris-gs"
spec:
  default:
    predictor:
      minReplicas: 1
      dependencies:
      	python: 3.7
      	pandas: 1.0.3
      	joblib: 0.4.1
      sklearn:
        storageUri: "gs://pct-tmp"

Ideally the kfserving execution system would examine the yaml and determine if the stock container for sklearn (a supported built-in model server) was compatible with the requested dependencies. If kfserving determined this was not true, then it would attempt to build a new docker image with the requested dependencies.

On the first container storage cold-cache run, then image would not exist so there would be a performance hit; The system would be building the image in the background, and we might reflect this with a STATUS column:

kubectl get inferenceservices                                 
NAME                URL   READY   DEFAULT TRAFFIC   CANARY TRAFFIC   AGE    STATUS
sklearn-iris-gs        False                                                                             2m.   BUILDING          

For every deploy after that using the same dependency requests, the pre-flight check would pick up the cached container (from gcr.io, artifactory, etc) and there would be no performance hit.

Obviously this adds complexity to the deployment logic, but would be easier for the average devops team than doing a custom inference service each time

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by nlarusstone** [comment]
This is something we would also really like and I wonder if we can model it off of how MLFlow does it: https://www.mlflow.org/docs/latest/projects.html#project-environments (though potentially without using conda)

**Comment by adriangonz** [comment]
Re-creating the environment from scratch every time adds some overhead. For MLflow models, Seldon supports [creating up the environment dynamically from a `conda.yaml` file](https://docs.seldon.io/projects/seldon-core/en/latest/servers/mlflow.html#conda-environment-creation). However, what we found out is that once you add a couple dependencies the time it takes to start up the pod just sky rockets. 

I'm not sure what could be a good way to cache these environments so that they can be re-used across runs.

Another option worth looking into is compiling the models to an intermediate format first. I haven't explored these much, but one could use something like [ONNX](https://github.com/onnx/onnx) or [microsoft/hummingbird](https://github.com/microsoft/hummingbird) so that the server only needs to deal with those. This would solve the problem of dealing with multiple framework versions and potentially even improve the server's performance.
